# Generated by Django 3.0.6 on 2020-05-10 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=64, null=True),
        ),
    ]
